### PR TITLE
add env PROTOCOL

### PR DESCRIPTION
**Pull request by Vq12da**

### CODE REVIEW

**Comment by uddr** [comment]
hello @Vq12da,
could you please describe a bit more what is the purpose of this PR?
Commit messages do not explain it as well

**Comment by novaflash** [comment]
It seems to me like they want to try be able to pass along settings with environment variables for which port/protocol to open VPN services on. But the way it's implemented doesn't actually change any of the settings in Access Server to actually change port/protocol.

For people reading this thread/PR, if you want Access Server to serve VPN services on another port and protocol, then just change this in how you launch docker, **and** change this in the Access Server settings. This can even be automated, it's not that hard.

**Comment by Vq12da** [comment]
@novaflash , wouldn't it work like this: we limit the port usage by protocol, since initially OpenVPN doesn't have a priority protocol, it uses the available one?

**Comment by novaflash** [comment]
No it won't work like that. What you've done is provide an environment control to tell Docker which port to allow to pass through - but the OpenVPN Access Server will still just listen to whatever ports it is configured to listen on. If you were to set PROTOCOL to TCP for example, you end up with the UDP 1194 port just becoming unreachable. Also, Access Server already by default listens for OpenVPN connections on UDP 1194 and TCP 443, so if you goal was to get OpenVPN working over TCP, that's already the case by default.

**Comment by uddr** [comment]
also @Vq12da, if you like to change port/protocol in the container or do not publish it at all, the best way to change this is with `-p` (publish) option but not by the `EXPOSE` in Dockerfile.
`publish` option does mapping when you run the container and you may choose any port/protocol you like no matter is exposed in Dockerfile. But first, Access Server should be configured to use it.
Having `EXPOSE <port>` configurable in Dockerfile does not provide any benefit because it works only inside the docker network and you have to rebuild the container every time you change the port.

**Comment by uddr** [comment]
I think we covered how to interact with ports/protocols
so this PR is not valid any more

**Pull request closed without merging**
